# Generated by Django 5.2.8 on 2025-11-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinculante', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
